### ISSUE TITLE
sequelize deprecated Instance.updateAttributes has been deprecated

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#36]
sequelize deprecated Instance.updateAttributes has been deprecated, please use Instance.update instead node_modules\sequelize\lib\model.js:4232:9

**Comment by chornbe** [comment]
Why? 
Is updateAttributes broken in some way? 
Is the functionality in update superior? 
If so, what differences are there? 
If so, why not turn updateAttributes into an API compliant wrapper around update so people don't have to update (pun!) potentially thousands of lines of code in a complex system. 

Rule #1 of API development - don't change your published API, instead version it and leave the old stuff alone, or compliance-wrap it so it all boils down to calling only the new code. :\ 

Microsoft pissed off a LOT of developers in the 90s by changing the ActiveX ADO libraries between version 2.0 and 2.1 without leaving any clean migration path. Since ADO is updated with system updates and not by developer inclusions, LOTS of software broke, literally over night in some cases. It was bad.

**Comment by rodrigorodriguez** [comment]
@chornbe, I agree with you and I lived the pain of such releases from MSFT, that's gone. We only manage [General Bots](https://github.com/generalbots/botbook) project which uses [Sequelize](https://github.com/sequelize/sequelize), a great database access library. @mickhansen [says](https://github.com/sequelize/sequelize/issues/2910#issuecomment-74409042) they are currently the same method.

I've updated all references to `instance.update` method. Thanks anyway.

**Comment by chornbe** [comment]
Yeah, my commentary was about the Sequelize authors doing this repeatedly, not about anyone relying on it :)

**Comment by mickhansen** [comment]
No software should be broken, if a method was removed i'm sure it happened under a semver major release. However i don't recall exactly when it was removed as i haven't been a maintainer for a long while.

**Comment by chornbe** [comment]
That's good to know. My questions still remain, and I'd love to get some feedback on them if only to satisfy my own macabre need of knowing how the sausage is made. :)

**Comment by mickhansen** [comment]
Not sure i can provide a complete answer as Sequelize has had multiple maintainers over time.
I suppose API changes like this mostly come from a place of wanting to provide a cleaner and more sane API over time.

**Comment by chornbe** [comment]
I guess there's always been, for me, a basic disconnect in the potential intuitive nature of it all...

There's updateAttributes({...}), there's .update(...), and there's .save(...)

Anyway, the horse is dead enough, and I don't mean to keep harping on it.

**Comment by mickhansen** [comment]
`updateAttributes` as a name made little sense, especially for new users, so over time we transitioned to really only have `update` and `save`

**Comment by chornbe** [comment]
I got into the habit early of using updateAttributes. IIRC, .save() only is useful when setting properties directly, such as:

obj.myName = "bob";
obj.yourName = "mickhansen";
obj.theDateToday = "2019 JUL 07";
obj.save().then(...);

... correct?

**Comment by mickhansen** [comment]
`save()` is used to save whatever properties have been modified via `set` (or direct access).

> and .update({...}) is a DIRECT replacement for .updateAttributes({...}) ?

I believe so, but it's probably been 2 years or more since i did work on Sequelize.
I recall `updateAttributes` proxying to `update`
